# Generated by Django 5.0.6 on 2024-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reg_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
