# Generated by Django 5.0.6 on 2024-06-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_studentprofile_id_alter_studentprofile_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
